[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty_dropdown"
class = "kitty_dropdown"
size = "50% 65%"

[scratchpads.clipse]
command = "kitty --class clipse sh -c 'clipse; pypr toggle clipse'"
class = "clipse"
size = "600px 576px"
animation = "fromBottom"
unfocus = "hide"
position = "1940px 844px"
lazy = true
