fork = true
frame = "full"
idle = true
maximized = false
vsync = false

[font]
normal = ["CaskaydiaCove Nerd Font Mono"]
size = 14.0

[font.features]
"CaskaydiaCove Nerd Font Mono" = ["+liga", "+ss01"]
